services:
  sqlserver:
    image: mcr.microsoft.com/mssql/server:2022-latest
    platform: linux/amd64
    container_name: stocksync-sqlserver
    environment:
      ACCEPT_EULA: "Y"
      SA_PASSWORD: "YourStrong!Passw0rd"
    ports:
      - "1434:1433"
    volumes:
      - stocksync-sql-data:/var/opt/mssql

  api:
    build:
      context: ./StockSync
      dockerfile: Dockerfile
    container_name: stocksync-api
    ports:
      - "8081:8080"
    environment:
      ASPNETCORE_ENVIRONMENT: Development
      ConnectionStrings__DefaultConnection: "Server=sqlserver,1433;Database=StockSyncDb;User Id=sa;Password=YourStrong!Passw0rd;TrustServerCertificate=True"
    depends_on:
      - sqlserver

  client:
    build:
      context: ./stocksync-client
      dockerfile: Dockerfile
    container_name: stocksync-client
    ports:
      - "8080:80"
    depends_on:
      - api

volumes:
  stocksync-sql-data: